// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6wNJzwW2r-iskGzo5-Go8gt6ZkADpzv8',
    appId: '1:835268026511:web:8f14184061f992115390fa',
    messagingSenderId: '835268026511',
    projectId: 'college-planner-b0aea',
    authDomain: 'college-planner-b0aea.firebaseapp.com',
    databaseURL: 'https://college-planner-b0aea-default-rtdb.firebaseio.com',
    storageBucket: 'college-planner-b0aea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-sH1VP2roMRbgCy9N896znvu_D96QWSY',
    appId: '1:835268026511:android:7b1d8fcaf73703115390fa',
    messagingSenderId: '835268026511',
    projectId: 'college-planner-b0aea',
    databaseURL: 'https://college-planner-b0aea-default-rtdb.firebaseio.com',
    storageBucket: 'college-planner-b0aea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWt-bKclLEeU2WKzGRaMFpjqljuzn7GSM',
    appId: '1:835268026511:ios:891527021fb67edb5390fa',
    messagingSenderId: '835268026511',
    projectId: 'college-planner-b0aea',
    databaseURL: 'https://college-planner-b0aea-default-rtdb.firebaseio.com',
    storageBucket: 'college-planner-b0aea.appspot.com',
    iosClientId: '835268026511-bosd50s1hbu9s6o4akmnr9a8ad0enr6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCodingMindsApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWt-bKclLEeU2WKzGRaMFpjqljuzn7GSM',
    appId: '1:835268026511:ios:891527021fb67edb5390fa',
    messagingSenderId: '835268026511',
    projectId: 'college-planner-b0aea',
    databaseURL: 'https://college-planner-b0aea-default-rtdb.firebaseio.com',
    storageBucket: 'college-planner-b0aea.appspot.com',
    iosClientId: '835268026511-bosd50s1hbu9s6o4akmnr9a8ad0enr6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCodingMindsApplication',
  );
}
